# Generated by Django 4.1.4 on 2022-12-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mydb.clones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CryptPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('pay_type', models.TextField(blank=True, null=True)),
                ('cancel_id', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('amount_rub', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'mydbcrypt_pay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField()),
                ('to_id', models.IntegerField()),
            ],
            options={
                'db_table': 'mydbhelper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.IntegerField()),
                ('pay_amount', models.IntegerField()),
                ('date', models.DateField()),
                ('pay_type', models.TextField()),
                ('user_id', models.IntegerField()),
                ('cancel_id', models.IntegerField()),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'mydbpay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('referrer_id', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('date_now', models.DateTimeField(blank=True, null=True)),
                ('link_name', models.TextField(blank=True, null=True)),
                ('depozit', models.IntegerField(blank=True, null=True)),
                ('gift_value', models.IntegerField(blank=True, null=True)),
                ('now_depozit', models.IntegerField(blank=True, null=True)),
                ('planet', models.TextField(blank=True, null=True)),
                ('step', models.TextField(blank=True, null=True)),
                ('first_dep', models.BooleanField()),
                ('status', models.BooleanField(blank=True, null=True)),
                ('count_ref', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('gift_money', models.IntegerField(blank=True, null=True)),
                ('amount_gift_money', models.IntegerField(blank=True, null=True)),
                ('ref_money', models.IntegerField(blank=True, null=True)),
                ('jump', models.BooleanField(blank=True, null=True)),
                ('last_withd', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mydbusers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('wallet', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mydbtransactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.TextField()),
                ('type', models.TextField()),
                ('amount', models.IntegerField()),
                ('data', models.TextField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'mydbwithdraw',
                'managed': False,
            },
        ),
    ]
