# Generated by Django 4.1.4 on 2022-12-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
        migrations.AlterModelOptions(
            name='cryptpay',
            options={'managed': False, 'verbose_name': 'Крипто-пополнение', 'verbose_name_plural': 'Крипто-пополнения'},
        ),
        migrations.AlterModelOptions(
            name='pay',
            options={'managed': False, 'verbose_name': 'Пополнение', 'verbose_name_plural': 'Пополнения'},
        ),
        migrations.AlterModelOptions(
            name='tguser',
            options={'managed': False, 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': False, 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterModelOptions(
            name='withdraw',
            options={'managed': False, 'verbose_name': 'Вывод', 'verbose_name_plural': 'Выводы'},
        ),
        migrations.AlterModelTable(
            name='clones',
            table='clones',
        ),
        migrations.AlterModelTable(
            name='cryptpay',
            table='crypt_pay',
        ),
        migrations.AlterModelTable(
            name='helper',
            table='helper',
        ),
        migrations.AlterModelTable(
            name='pay',
            table='pay',
        ),
        migrations.AlterModelTable(
            name='tguser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
        migrations.AlterModelTable(
            name='withdraw',
            table='withdraw',
        ),
    ]
