# Generated by Django 4.1.4 on 2022-12-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_panel', '0002_apitokens_alter_cryptpay_options_alter_pay_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Статистика',
                'db_table': 'tg_panel_statistic',
            },
        ),
        migrations.AlterField(
            model_name='apitokens',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
