# Generated by Django 4.1.4 on 2022-12-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_panel', '0003_statistic_alter_apitokens_title'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statistic',
            table=None,
        ),
    ]
