# Generated by Django 4.1.4 on 2022-12-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_panel', '0004_alter_statistic_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('ref_id', models.IntegerField(verbose_name='ID реферала')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'db_table': 'ref_money',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllStats',
            fields=[
            ],
            options={
                'verbose_name': 'Общая статистика',
                'verbose_name_plural': 'Общая статистика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tg_panel.tguser',),
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'managed': False, 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.RemoveField(
            model_name='apitokens',
            name='token',
        ),
        migrations.AddField(
            model_name='apitokens',
            name='api',
            field=models.CharField(default='api', max_length=300, verbose_name='Токен'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apitokens',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
