# Generated by Django 3.2.12 on 2023-01-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_panel', '0005_refmoney_allstats_alter_statistic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apitokens',
            table='tokens',
        ),
        migrations.AlterModelTable(
            name='statistic',
            table='users',
        ),
    ]
